# Generated by Django 2.2.3 on 2019-07-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('player_1', models.CharField(blank=True, max_length=100, null=True)),
                ('player_2', models.CharField(blank=True, max_length=100, null=True)),
                ('player_3', models.CharField(blank=True, max_length=100, null=True)),
                ('player_4', models.CharField(blank=True, max_length=100, null=True)),
                ('player_5', models.CharField(blank=True, max_length=100, null=True)),
                ('player_6', models.CharField(blank=True, max_length=100, null=True)),
                ('player_7', models.CharField(blank=True, max_length=100, null=True)),
                ('player_8', models.CharField(blank=True, max_length=100, null=True)),
                ('player_9', models.CharField(blank=True, max_length=100, null=True)),
                ('player_10', models.CharField(blank=True, max_length=100, null=True)),
                ('player_11', models.CharField(blank=True, max_length=100, null=True)),
                ('player_12', models.CharField(blank=True, max_length=100, null=True)),
                ('player_13', models.CharField(blank=True, max_length=100, null=True)),
                ('player_14', models.CharField(blank=True, max_length=100, null=True)),
                ('player_15', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('regional', 'Regional'), ('district', 'District')], max_length=100)),
                ('tournament_type', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football')], max_length=100)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze_medalist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_runner_up', to='player.Team')),
                ('gold_medalist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='player.Team')),
                ('silver_medalist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_runner_up', to='player.Team')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Tournament'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('team_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='player.Team')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='player.Team')),
            ],
        ),
    ]
