# Generated by Django 2.2.3 on 2019-07-14 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_team_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
