# Generated by Django 2.2.3 on 2019-07-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_team_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
